# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python-password-generator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 870)
        Form.setMinimumSize(QtCore.QSize(480, 870))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        Form.setFont(font)
        self.showPasswordLineEdit = QtWidgets.QLineEdit(Form)
        self.showPasswordLineEdit.setGeometry(QtCore.QRect(40, 20, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showPasswordLineEdit.setFont(font)
        self.showPasswordLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.showPasswordLineEdit.setReadOnly(True)
        self.showPasswordLineEdit.setClearButtonEnabled(False)
        self.showPasswordLineEdit.setObjectName("showPasswordLineEdit")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 160, 162, 157))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.incVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.incVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.incVerticalLayout.setObjectName("incVerticalLayout")
        self.bUpperLetterCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.bUpperLetterCheckBox.setChecked(True)
        self.bUpperLetterCheckBox.setObjectName("bUpperLetterCheckBox")
        self.incVerticalLayout.addWidget(self.bUpperLetterCheckBox)
        self.bLowerLetterCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.bLowerLetterCheckBox.setChecked(True)
        self.bLowerLetterCheckBox.setObjectName("bLowerLetterCheckBox")
        self.incVerticalLayout.addWidget(self.bLowerLetterCheckBox)
        self.bDigitCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.bDigitCheckBox.setChecked(True)
        self.bDigitCheckBox.setObjectName("bDigitCheckBox")
        self.incVerticalLayout.addWidget(self.bDigitCheckBox)
        self.bSymbolCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.bSymbolCheckBox.setChecked(True)
        self.bSymbolCheckBox.setObjectName("bSymbolCheckBox")
        self.incVerticalLayout.addWidget(self.bSymbolCheckBox)
        self.lengthLabel = QtWidgets.QLabel(Form)
        self.lengthLabel.setGeometry(QtCore.QRect(40, 110, 40, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lengthLabel.setFont(font)
        self.lengthLabel.setObjectName("lengthLabel")
        self.lengthSpinBox = QtWidgets.QSpinBox(Form)
        self.lengthSpinBox.setGeometry(QtCore.QRect(280, 110, 160, 35))
        self.lengthSpinBox.setMinimum(4)
        self.lengthSpinBox.setMaximum(256)
        self.lengthSpinBox.setProperty("value", 8)
        self.lengthSpinBox.setObjectName("lengthSpinBox")
        self.incLabel = QtWidgets.QLabel(Form)
        self.incLabel.setGeometry(QtCore.QRect(40, 220, 40, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.incLabel.setFont(font)
        self.incLabel.setObjectName("incLabel")
        self.listHowToLabel = QtWidgets.QLabel(Form)
        self.listHowToLabel.setGeometry(QtCore.QRect(40, 660, 130, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listHowToLabel.setFont(font)
        self.listHowToLabel.setObjectName("listHowToLabel")
        self.howToComboBox = QtWidgets.QComboBox(Form)
        self.howToComboBox.setGeometry(QtCore.QRect(360, 660, 80, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.howToComboBox.setFont(font)
        self.howToComboBox.setObjectName("howToComboBox")
        self.howToComboBox.addItem("")
        self.howToComboBox.addItem("")
        self.splitListLabel = QtWidgets.QLabel(Form)
        self.splitListLabel.setGeometry(QtCore.QRect(40, 710, 140, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.splitListLabel.setFont(font)
        self.splitListLabel.setObjectName("splitListLabel")
        self.minLengthGroupBox = QtWidgets.QGroupBox(Form)
        self.minLengthGroupBox.setGeometry(QtCore.QRect(30, 340, 420, 240))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.minLengthGroupBox.setFont(font)
        self.minLengthGroupBox.setObjectName("minLengthGroupBox")
        self.lenUpperLetterLabel = QtWidgets.QLabel(self.minLengthGroupBox)
        self.lenUpperLetterLabel.setGeometry(QtCore.QRect(10, 40, 61, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lenUpperLetterLabel.setFont(font)
        self.lenUpperLetterLabel.setObjectName("lenUpperLetterLabel")
        self.lenLowerLetterLabel = QtWidgets.QLabel(self.minLengthGroupBox)
        self.lenLowerLetterLabel.setGeometry(QtCore.QRect(10, 90, 60, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lenLowerLetterLabel.setFont(font)
        self.lenLowerLetterLabel.setObjectName("lenLowerLetterLabel")
        self.lenDigitsLabel = QtWidgets.QLabel(self.minLengthGroupBox)
        self.lenDigitsLabel.setGeometry(QtCore.QRect(10, 140, 70, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lenDigitsLabel.setFont(font)
        self.lenDigitsLabel.setObjectName("lenDigitsLabel")
        self.lenSymbolLabel = QtWidgets.QLabel(self.minLengthGroupBox)
        self.lenSymbolLabel.setGeometry(QtCore.QRect(10, 190, 80, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lenSymbolLabel.setFont(font)
        self.lenSymbolLabel.setObjectName("lenSymbolLabel")
        self.lenUpperLetterSpinBox = QtWidgets.QSpinBox(self.minLengthGroupBox)
        self.lenUpperLetterSpinBox.setGeometry(QtCore.QRect(250, 40, 160, 35))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lenUpperLetterSpinBox.setFont(font)
        self.lenUpperLetterSpinBox.setMinimum(0)
        self.lenUpperLetterSpinBox.setMaximum(64)
        self.lenUpperLetterSpinBox.setProperty("value", 1)
        self.lenUpperLetterSpinBox.setObjectName("lenUpperLetterSpinBox")
        self.lenLowerLetterSpinBox = QtWidgets.QSpinBox(self.minLengthGroupBox)
        self.lenLowerLetterSpinBox.setGeometry(QtCore.QRect(250, 90, 160, 35))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lenLowerLetterSpinBox.setFont(font)
        self.lenLowerLetterSpinBox.setMinimum(1)
        self.lenLowerLetterSpinBox.setMaximum(64)
        self.lenLowerLetterSpinBox.setProperty("value", 1)
        self.lenLowerLetterSpinBox.setObjectName("lenLowerLetterSpinBox")
        self.lenDigitsSpinBox = QtWidgets.QSpinBox(self.minLengthGroupBox)
        self.lenDigitsSpinBox.setGeometry(QtCore.QRect(250, 140, 160, 35))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lenDigitsSpinBox.setFont(font)
        self.lenDigitsSpinBox.setMinimum(1)
        self.lenDigitsSpinBox.setMaximum(64)
        self.lenDigitsSpinBox.setProperty("value", 1)
        self.lenDigitsSpinBox.setObjectName("lenDigitsSpinBox")
        self.lenSymbolSpinBox = QtWidgets.QSpinBox(self.minLengthGroupBox)
        self.lenSymbolSpinBox.setGeometry(QtCore.QRect(250, 190, 160, 35))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lenSymbolSpinBox.setFont(font)
        self.lenSymbolSpinBox.setMinimum(1)
        self.lenSymbolSpinBox.setMaximum(64)
        self.lenSymbolSpinBox.setProperty("value", 1)
        self.lenSymbolSpinBox.setObjectName("lenSymbolSpinBox")
        self.GeneratePushButton = QtWidgets.QPushButton(Form)
        self.GeneratePushButton.setGeometry(QtCore.QRect(40, 790, 400, 60))
        self.GeneratePushButton.setObjectName("GeneratePushButton")
        self.listLineEdit = QtWidgets.QLineEdit(Form)
        self.listLineEdit.setGeometry(QtCore.QRect(40, 610, 400, 40))
        self.listLineEdit.setObjectName("listLineEdit")
        self.listLineEdit_2 = QtWidgets.QLineEdit(Form)
        self.listLineEdit_2.setGeometry(QtCore.QRect(360, 710, 80, 30))
        self.listLineEdit_2.setObjectName("listLineEdit_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Random Password Generator"))
        self.showPasswordLineEdit.setToolTip(_translate("Form", "\'비밀번호 생성하기\' 버튼을 눌러 비밀번호를 생성할 수 있습니다."))
        self.showPasswordLineEdit.setPlaceholderText(_translate("Form", "이곳에 비밀번호가 표시됩니다."))
        self.bUpperLetterCheckBox.setToolTip(_translate("Form", "체크하면 비밀번호에 대문자를 포함합니다."))
        self.bUpperLetterCheckBox.setText(_translate("Form", "대문자 포함"))
        self.bLowerLetterCheckBox.setToolTip(_translate("Form", "체크하면 비밀번호에 소문자를 포함합니다."))
        self.bLowerLetterCheckBox.setText(_translate("Form", "소문자 포함"))
        self.bDigitCheckBox.setToolTip(_translate("Form", "체크하면 비밀번호에 숫자를 포함합니다."))
        self.bDigitCheckBox.setText(_translate("Form", "숫자 포함"))
        self.bSymbolCheckBox.setToolTip(_translate("Form", "체크하면 비밀번호에 특수문자를 포함합니다."))
        self.bSymbolCheckBox.setText(_translate("Form", "특수문자 포함"))
        self.lengthLabel.setText(_translate("Form", "길이"))
        self.lengthSpinBox.setToolTip(_translate("Form", "비밀번호 길이를 정합니다. (4~256)"))
        self.incLabel.setText(_translate("Form", "포함"))
        self.listHowToLabel.setText(_translate("Form", "입력한 문자를"))
        self.howToComboBox.setToolTip(_translate("Form", "입력한 문자를 제외할지, 포함할지 정합니다."))
        self.howToComboBox.setItemText(0, _translate("Form", "제외"))
        self.howToComboBox.setItemText(1, _translate("Form", "포함"))
        self.splitListLabel.setText(_translate("Form", "문자 구분 방법"))
        self.minLengthGroupBox.setTitle(_translate("Form", "최소 길이 설정"))
        self.lenUpperLetterLabel.setText(_translate("Form", "대문자"))
        self.lenLowerLetterLabel.setText(_translate("Form", "소문자"))
        self.lenDigitsLabel.setText(_translate("Form", "숫자"))
        self.lenSymbolLabel.setText(_translate("Form", "특수문자"))
        self.lenUpperLetterSpinBox.setToolTip(_translate("Form", "비밀번호에 대문자가 최소 몇 자 있어야 하는지 정합니다. (1~64)"))
        self.lenLowerLetterSpinBox.setToolTip(_translate("Form", "비밀번호에 소문자가 최소 몇 자 있어야 하는지 정합니다. (1~64)"))
        self.lenDigitsSpinBox.setToolTip(_translate("Form", "비밀번호에 숫자가 최소 몇 자 있어야 하는지 정합니다. (1~64)"))
        self.lenSymbolSpinBox.setToolTip(_translate("Form", "비밀번호에 특수문자가 최소 몇 자 있어야 하는지 정합니다. (1~64)"))
        self.GeneratePushButton.setToolTip(_translate("Form", "클릭하면 설정에 맞는 비밀번호를 생성합니다."))
        self.GeneratePushButton.setText(_translate("Form", "비밀번호 생성하기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

